<a href="https://colab.research.google.com/github/nadiralam/data-science-machine-learning-AtoZ-tutorials/blob/main/01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# create numpy array

np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# 2D

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D

c = np.array([[[1,2,],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype

d = np.array([4,7,9], dtype = float)
print(d)

[4. 7. 9.]


In [ ]:
d = np.array([4,7,9], dtype = bool)
print(d)

[ True  True  True]


In [ ]:
d = np.array([4,7,9], dtype = complex)
print(d)

[4.+0.j 7.+0.j 9.+0.j]


In [ ]:
# arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# random

np.random.random((3,4))

array([[0.00242229, 0.36576052, 0.04448634, 0.47719858],
       [0.4380071 , 0.67019132, 0.46558022, 0.61865126],
       [0.03750467, 0.83388745, 0.57895274, 0.27959482]])

In [ ]:
# linspace

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# reshape

np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.arange(0,12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
# np.ones

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# np.zeros

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a1 = np.arange(1,11)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# **Array Attributes**

In [ ]:
# ndim

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
# shape

print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
# size

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [ ]:
# itemsize

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [ ]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
int64
int64


# **Array data type change**

In [ ]:
# astype

print(a1.astype(np.int32))
print(a2.astype(np.int32))
a3.astype(np.int32)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## **Array Operation**

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(a2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# scalar operation

# Arithematic

a1 +2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a1 *2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a1 /2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
# Realtional

a2 >5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 >25

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a2 >15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a2 != 15

array([[ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# Vector operations

# Arithmetic

a1 + a2


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1 *a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [ ]:
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# **Array Function**

In [ ]:
a1 = np.random.random((3,4))
print(a1)

[[0.90966406 0.00319162 0.89980521 0.4166291 ]
 [0.57673812 0.26543778 0.49142161 0.86798229]
 [0.34285341 0.67079641 0.1411573  0.95615451]]


In [ ]:
a1 = a1 *100
print(a1)

[[90.96640568  0.31916217 89.9805214  41.6629103 ]
 [57.67381195 26.54377786 49.14216113 86.79822854]
 [34.28534131 67.07964116 14.11572969 95.6154515 ]]


In [ ]:
# round
a1 = np.round(a1)
print(a1)

[[91.  0. 90. 42.]
 [58. 27. 49. 87.]
 [34. 67. 14. 96.]]


In [ ]:
# max/min/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

96.0
0.0
655.0
0.0


In [ ]:
# find max/min element  in row
print(np.max(a1,axis = 1))
print(np.min(a1,axis = 1))
print(np.sum(a1,axis = 1))
print(np.prod(a1,axis = 1))

[91. 87. 96.]
[ 0. 27. 14.]
[223. 221. 211.]
[      0. 6675858. 3061632.]


In [ ]:
# in column
print(np.max(a1,axis = 0))
print(np.min(a1,axis = 0))
print(np.sum(a1,axis = 0))
print(np.prod(a1,axis = 0))

[91. 67. 90. 96.]
[34.  0. 14. 42.]
[183.  94. 153. 225.]
[179452.      0.  61740. 350784.]


In [ ]:
# mean/median/std/var

print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

54.583333333333336
53.5
30.97433973827727
959.4097222222223


In [ ]:
# in row

print(np.mean(a1,axis = 1))
print(np.median(a1,axis = 1))
print(np.std(a1,axis = 1))
print(np.var(a1,axis = 1))

[55.75 55.25 52.75]
[66.  53.5 50.5]
[37.79136806 21.52179128 31.3318927 ]
[1428.1875  463.1875  981.6875]


In [ ]:
# in column

print(np.mean(a1,axis = 0))
print(np.median(a1,axis = 0))
print(np.std(a1,axis = 0))
print(np.var(a1,axis = 0))

[61.         31.33333333 51.         75.        ]
[58. 27. 49. 87.]
[23.36664289 27.52372714 31.05908348 23.62202362]
[546.         757.55555556 964.66666667 558.        ]


In [ ]:
# Trignometric function

np.sin(a1)

array([[ 0.10598751,  0.        ,  0.89399666, -0.91652155],
       [ 0.99287265,  0.95637593, -0.95375265, -0.82181784],
       [ 0.52908269, -0.85551998,  0.99060736,  0.98358775]])

In [ ]:
np.cos(a1)

array([[-0.99436746,  1.        , -0.44807362, -0.39998531],
       [ 0.11918014, -0.29213881,  0.30059254,  0.56975033],
       [-0.84857027, -0.5177698 ,  0.13673722, -0.18043045]])

In [ ]:
np.tan(a1)

array([[-0.10658787,  0.        , -1.99520041,  2.29138799],
       [ 8.33085685, -3.2737038 , -3.17290855, -1.44241747],
       [-0.62349896,  1.65231726,  7.24460662, -5.45134011]])

In [ ]:
b1 =np.arange(12).reshape(3,4)
print(b1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
b2 = np.arange(12,24).reshape(4,3)
print(b2)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [ ]:
# Dot Product

np.dot(b1,b2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# Log and Exponents

np.log(a1)

<ipython-input-203-4fc891df45a6>:3: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[4.51085951,       -inf, 4.49980967, 3.73766962],
       [4.06044301, 3.29583687, 3.8918203 , 4.46590812],
       [3.52636052, 4.20469262, 2.63905733, 4.56434819]])

In [ ]:
np.exp(a1)

array([[3.31740010e+39, 1.00000000e+00, 1.22040329e+39, 1.73927494e+18],
       [1.54553894e+25, 5.32048241e+11, 1.90734657e+21, 6.07603023e+37],
       [5.83461743e+14, 1.25236317e+29, 1.20260428e+06, 4.92345829e+41]])

In [ ]:
# Round/ceil/floor

c1 = np.random.random((2,3))*100
print(c1)

[[61.94924439 95.3802736  57.24819737]
 [72.70297253 75.2304199  19.90839528]]


In [ ]:
# round
np.round(c1)

array([[62., 95., 57.],
       [73., 75., 20.]])

In [ ]:
# ceil

np.ceil(c1)

array([[62., 96., 58.],
       [73., 76., 20.]])

In [ ]:
# floor
np.floor(c1)

array([[61., 95., 57.],
       [72., 75., 19.]])

# **Indexing and Slicing**

In [ ]:
c1 = np.arange(12)
c2 = np.arange(12).reshape(3,4)
c3 = np.arange(8).reshape(2,2,2)

In [ ]:
c3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# Indexing

c1[-1]

11

In [ ]:
c1[0]

0

In [ ]:
c2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
c2[1,1]

5

In [ ]:
c2[1,3]

7

In [ ]:
c2[2,2]

10

In [ ]:
c3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
c3[0,1,1]

3

In [ ]:
c3[1,0,1]

5

In [ ]:
# Slicing

c1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
c1[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
c1[2:7]

array([2, 3, 4, 5, 6])

In [ ]:
c2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
c2[0,:]

array([0, 1, 2, 3])

In [ ]:
c2[1,:]

array([4, 5, 6, 7])

In [ ]:
c2[:,2]

array([ 2,  6, 10])

In [ ]:
c2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
c2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
c2[1:,::2]

array([[ 4,  6],
       [ 8, 10]])

In [ ]:
c3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
c3[1,:,1]

array([5, 7])

In [ ]:
c3[0,1,:]

array([2, 3])

# **Iteration**

In [ ]:
c1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
c2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
c3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
for i in c1:
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for i in c2:
  print(i)


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in c3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
for i in np.ravel(c2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for i in np.ravel(c3):
  print(i)

0
1
2
3
4
5
6
7


In [ ]:
# Transpose

c2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(c2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
c2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# **Stacking**

In [ ]:
c4 = np.arange(12).reshape(3,4)
c5 = np.arange(12,24).reshape(3,4)

In [ ]:
c4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
c5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# hstack

np.hstack((c4,c5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# vstack

np.vstack((c4,c5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# **Splitting**

In [ ]:
# hsplit

np.hsplit(c4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vsplit
np.vsplit(c5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]