<a href="https://colab.research.google.com/github/nadiralam/data-science-machine-learning-AtoZ-tutorials/blob/main/03_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# **sorting**

In [ ]:
a  = np.random.randint(1,50,15)
b = np.random.randint(1,100,24).reshape(6,4)

In [ ]:
print(a)
print(b)

[12 39  9 25 21 19 42 21 36 47 19 23 43 20 47]
[[ 2  8 87 74]
 [10 28 83 71]
 [ 6 51 83 94]
 [72  6 12 70]
 [29 49 98 21]
 [ 9  4 74 61]]


In [ ]:
# sorting in ascending order

np.sort(a)

array([ 9, 12, 19, 19, 20, 21, 21, 23, 25, 36, 39, 42, 43, 47, 47])

In [ ]:
# sorting in descending order

np.sort(a)[::-1]

array([47, 47, 43, 42, 39, 36, 25, 23, 21, 21, 20, 19, 19, 12,  9])

In [ ]:
np.sort(b,axis = 1) # ---------> row wise sorting

array([[ 2,  8, 74, 87],
       [10, 28, 71, 83],
       [ 6, 51, 83, 94],
       [ 6, 12, 70, 72],
       [21, 29, 49, 98],
       [ 4,  9, 61, 74]])

In [ ]:
np.sort(b,axis = 0) # ---------> column wise sorting

array([[ 2,  4, 12, 21],
       [ 6,  6, 74, 61],
       [ 9,  8, 83, 70],
       [10, 28, 83, 71],
       [29, 49, 87, 74],
       [72, 51, 98, 94]])

# **Append**

In [ ]:
np.append(a,200)

array([ 12,  39,   9,  25,  21,  19,  42,  21,  36,  47,  19,  23,  43,
        20,  47, 200])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[ 2.,  8., 87., 74.,  1.],
       [10., 28., 83., 71.,  1.],
       [ 6., 51., 83., 94.,  1.],
       [72.,  6., 12., 70.,  1.],
       [29., 49., 98., 21.,  1.],
       [ 9.,  4., 74., 61.,  1.]])

# **Concatenate**

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [ ]:
np.concatenate((c,d)) # ----------> row wise

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis = 1) #--------> column wise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# **Unique**

In [ ]:
e = np.array([1,1,1,1,2,2,33,5,5,6,7,7,7,8,8])

In [ ]:
np.unique(e)

array([ 1,  2,  5,  6,  7,  8, 33])

# **expand_dims**

In [ ]:
a

array([12, 39,  9, 25, 21, 19, 42, 21, 36, 47, 19, 23, 43, 20, 47])

In [ ]:
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis = 0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis = 1)

array([[12],
       [39],
       [ 9],
       [25],
       [21],
       [19],
       [42],
       [21],
       [36],
       [47],
       [19],
       [23],
       [43],
       [20],
       [47]])

In [ ]:
np.expand_dims(a,axis = 1).shape

(15, 1)

# **Where**

In [ ]:
a

array([12, 39,  9, 25, 21, 19, 42, 21, 36, 47, 19, 23, 43, 20, 47])

In [ ]:
np.where(a>25)

(array([ 1,  6,  8,  9, 12, 14]),)

In [ ]:
b

array([[ 2,  8, 87, 74],
       [10, 28, 83, 71],
       [ 6, 51, 83, 94],
       [72,  6, 12, 70],
       [29, 49, 98, 21],
       [ 9,  4, 74, 61]])

In [ ]:
# replace all values > 25 with 0

np.where(a>25,0,a)

array([12,  0,  9, 25, 21, 19,  0, 21,  0,  0, 19, 23,  0, 20,  0])

In [ ]:
# all even repalces with 0

np.where(a%2==0,0,a)

array([ 0, 39,  9, 25, 21, 19,  0, 21,  0, 47, 19, 23, 43,  0, 47])

# **Argmax**

In [ ]:
a

array([12, 39,  9, 25, 21, 19, 42, 21, 36, 47, 19, 23, 43, 20, 47])

In [ ]:
np.argmax(a)

9

In [ ]:
b

array([[ 2,  8, 87, 74],
       [10, 28, 83, 71],
       [ 6, 51, 83, 94],
       [72,  6, 12, 70],
       [29, 49, 98, 21],
       [ 9,  4, 74, 61]])

In [ ]:
np.argmax(b,axis = 0)

array([3, 2, 4, 2])

In [ ]:
np.argmax(b,axis = 1)

array([2, 2, 3, 0, 2, 2])

# **argmin**

In [ ]:
np.argmin(a)

2

In [ ]:
np.argmin(b,axis = 1)

array([0, 0, 0, 1, 3, 1])

# **cumsum**

In [ ]:
a

array([12, 39,  9, 25, 21, 19, 42, 21, 36, 47, 19, 23, 43, 20, 47])

In [ ]:
np.cumsum(a)

array([ 12,  51,  60,  85, 106, 125, 167, 188, 224, 271, 290, 313, 356,
       376, 423])

In [ ]:
b

array([[ 2,  8, 87, 74],
       [10, 28, 83, 71],
       [ 6, 51, 83, 94],
       [72,  6, 12, 70],
       [29, 49, 98, 21],
       [ 9,  4, 74, 61]])

In [ ]:
np.cumsum(b,axis = 1)

array([[  2,  10,  97, 171],
       [ 10,  38, 121, 192],
       [  6,  57, 140, 234],
       [ 72,  78,  90, 160],
       [ 29,  78, 176, 197],
       [  9,  13,  87, 148]])

In [ ]:
np.cumsum(b,axis = 0)

array([[  2,   8,  87,  74],
       [ 12,  36, 170, 145],
       [ 18,  87, 253, 239],
       [ 90,  93, 265, 309],
       [119, 142, 363, 330],
       [128, 146, 437, 391]])

# **cumprod**

In [ ]:
a

array([12, 39,  9, 25, 21, 19, 42, 21, 36, 47, 19, 23, 43, 20, 47])

In [ ]:
np.cumprod(a)

array([                 12,                 468,                4212,
                    105300,             2211300,            42014700,
                1764617400,         37056965400,       1334050754400,
            62700385456800,    1191307323679200,   27400068444621600,
       1178202943118728800, 5117314788665024384,  706122109031975040])

# **Percentile**

In [ ]:
a

array([12, 39,  9, 25, 21, 19, 42, 21, 36, 47, 19, 23, 43, 20, 47])

In [ ]:
np.percentile(a,50)

23.0

In [ ]:
np.percentile(a,100)

47.0

# **Histogram**

In [ ]:
a

array([12, 39,  9, 25, 21, 19, 42, 21, 36, 47, 19, 23, 43, 20, 47])

In [ ]:
np.histogram(a,bins = [1,25,50])

(array([8, 7]), array([ 1, 25, 50]))

# **Corrcoef**

In [ ]:
salary = np.array([20000,40000,50000,60000])
experience = np.array([1,3,2,4])

np.corrcoef(salary,experience)

array([[1.        , 0.83152184],
       [0.83152184, 1.        ]])

# **Isin**

In [ ]:
a

array([12, 39,  9, 25, 21, 19, 42, 21, 36, 47, 19, 23, 43, 20, 47])

In [ ]:
item = np.array([12,45,56,33,22,44,11,77,43,23])

In [ ]:
np.isin(item ,a)

array([ True, False, False, False, False, False, False, False,  True,
        True])

In [ ]:
item[np.isin(item ,a)]

array([12, 43, 23])

# **Flip**

In [ ]:
a

array([12, 39,  9, 25, 21, 19, 42, 21, 36, 47, 19, 23, 43, 20, 47])

In [ ]:
np.flip(a)

array([47, 20, 43, 23, 19, 47, 36, 21, 42, 19, 21, 25,  9, 39, 12])

# **Put**

In [ ]:
a

array([12, 39,  9, 25, 21, 19, 42, 21, 36, 47, 19, 23, 43, 20, 47])

In [ ]:
np.put(a,[0,1],[120,150])

In [ ]:
a

array([120, 150,   9,  25,  21,  19,  42,  21,  36,  47,  19,  23,  43,
        20,  47])

# **Delete**

In [ ]:
a

array([120, 150,   9,  25,  21,  19,  42,  21,  36,  47,  19,  23,  43,
        20,  47])

In [ ]:
np.delete(a,[0,1])

array([ 9, 25, 21, 19, 42, 21, 36, 47, 19, 23, 43, 20, 47])

# **Set Function**

In [ ]:
# np.union1d

e = np.array([1,2,3,4,5])
f = np.array([3,4,5,6,7])

np.union1d(e,f)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# np.intersect1d

e = np.array([1,2,3,4,5])
f = np.array([3,4,5,6,7])

np.intersect1d(e,f)

array([3, 4, 5])

In [ ]:
# np.setdiff1d

e = np.array([1,2,3,4,5])
f = np.array([3,4,5,6,7])

np.setdiff1d(e,f)

array([1, 2])

In [ ]:
# np.setxor1d

e = np.array([1,2,3,4,5])
f = np.array([3,4,5,6,7])

np.setxor1d(e,f)

array([1, 2, 6, 7])

In [ ]:
# np.in1d

e = np.array([1,2,3,4,5])
f = np.array([3,4,5,6,7])

np.in1d(e,f)

array([False, False,  True,  True,  True])

In [ ]:
e[np.in1d(e,f)]

array([3, 4, 5])

# **Clip**

In [ ]:
a

array([120, 150,   9,  25,  21,  19,  42,  21,  36,  47,  19,  23,  43,
        20,  47])

In [ ]:
np.clip(a,a_max = 50, a_min = 10)

array([50, 50, 10, 25, 21, 19, 42, 21, 36, 47, 19, 23, 43, 20, 47])